vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set number")
vim.cmd("set numberwidth=4")
vim.cmd("set nowrap")
vim.cmd("set autoindent")
vim.cmd("set expandtab")
vim.cmd("set encoding=utf8")

